name: Issue
description: Report an issue with one of the samples in this repository. 
body:
  - type: checkboxes
    attributes:
      label: IMPORTANT
      description: Verify the following requirements have been met before opening an issue.
      options:
        - label: My question is related to the samples and content within this repository. For all other issues, open a ticket with [Esri Technical Support](https://support.esri.com/) or post your question in the [community forum](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
          required: true
        - label: I have [checked for existing issues](https://github.com/Esri/jsapi-resources/issues) to avoid duplicates. If someone has already opened an issue for what you are experiencing, please add a 👍 reaction and comment as necessary to the existing issue instead of creating a new one. You can also refer to this repo's [troubleshooting guide](https://developers.arcgis.com/javascript/latest/troubleshooting/) for hints and suggestions.
          required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear description of the issue and the complete error message from the browser console. If applicable provide screenshots, console messages and network request/response information. If this issue has been posted elsewhere, add a reference here.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen and why?
    validations:
      required: true
  - type: input
    id: sample
    attributes:
      label: Reproduction sample
      description: |
        We require a link to a GitHub repository, codepen or equivalent so that we can reproduce the issue locally.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Clear, numbered steps for reproducing the issue using the sample provided above.
      placeholder: |
        1. Open the DevTools console
        2. Click on XYZ
        3. ...
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Reproduction browser
      description: Browser (check https://whatismybrowser.com/)
      placeholder: e.g. Chrome 130 on Windows 11
    validations:
      required: true
  - type: textarea
    id: operatingsystem
    attributes:
      label: Operating System (check https://whatsmyos.com)
      description: Provide the operating system version and device make/model.
      placeholder: |
        - OS:
            e.g. Apple iOS 18, Windows 10* 64-bit or MacOS 14.7
        - Device:
            e.g. iPhone 15, Samsung Galaxy S24 or MacBook Pro
        ...
    validations:
      required: true
